.pragma library

// Pure renderer. Main.qml computes the workspace names (so the naming scheme lives
// in one place); this just renders KDL. No I/O.

function escapeRegex(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// workspaces: [{name, output}]   rules: [{appId, title, wsName}]
function generate(workspaces, rules) {
  var lines = [];
  lines.push("// AUTO-GENERATED by the Noctalia \"Workspace Profiles\" plugin.");
  lines.push("// Do not edit by hand — regenerated on every change.");
  lines.push("");

  for (var i = 0; i < workspaces.length; i++) {
    var w = workspaces[i];
    if (!w.name) continue;
    if (w.output)
      lines.push("workspace \"" + w.name + "\" { open-on-output \"" + w.output + "\"; }");
    else
      lines.push("workspace \"" + w.name + "\" {}");
  }
  lines.push("");

  for (var j = 0; j < rules.length; j++) {
    var r = rules[j];
    if (!r.appId || !r.wsName) continue;
    lines.push("window-rule {");
    var m = "    match app-id=r#\"^" + escapeRegex(r.appId) + "$\"#";
    if (r.title && r.title.length) m += " title=r#\"" + r.title + "\"#";
    lines.push(m);
    lines.push("    open-on-workspace \"" + r.wsName + "\"");
    lines.push("}");
  }

  return lines.join("\n") + "\n";
}
